customhost = "projectdb.ce8kthfghagr.us-east-1.rds.amazonaws.com"
customuser = "parthiban"
custompass = "parthiban123"
customdb = "projectdb"
custombucket = "databases2029"
customregion = "us-east-2"
